In [ ]:
"""
This assignment consists of five questions for a total of 75 points. Submit your results as a .py file via your GitHub repository.
1. Import numpy as np and print the version number. (5 Points)
2. Create a 1D array of numbers from 0 to 9. Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
(10 Points)

3. Import a dataset with numbers and texts keeping the text intact in python numpy. Use the iris dataset available from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.dataLinks to an external site.. (20 Points)

4. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset. Use the iris dataset available from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.dataLinks to an external site.. (20 Points)

5. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
Input:

np.random.seed(100)
a = np.random.uniform(1,50, 20)
(20 Points)
"""

In [3]:
# 1. Import numpy as np and print the version number. (5 Points)
import numpy as np

In [9]:
# 2. Create a 1D array of numbers from 0 to 9. Desired output:
# #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# (10 Points)

Q2 = np.arange(10)
print(Q2)

[0 1 2 3 4 5 6 7 8 9]


In [85]:
# 3. Import a dataset with numbers and texts keeping the text intact in python numpy. 
# Use the iris dataset available from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.dataLinks to an external site.. 
# (20 Points)
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_data = np.genfromtxt(url, delimiter=',', dtype=None)
iris_numeric_data = np.array(iris_data[:], dtype= None)
print(iris_data[:20])

[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, b'Iris-setosa') (5.4, 3.9, 1.7, 0.4, b'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, b'Iris-setosa') (5. , 3.4, 1.5, 0.2, b'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, b'Iris-setosa') (4.9, 3.1, 1.5, 0.1, b'Iris-setosa')
 (5.4, 3.7, 1.5, 0.2, b'Iris-setosa') (4.8, 3.4, 1.6, 0.2, b'Iris-setosa')
 (4.8, 3. , 1.4, 0.1, b'Iris-setosa') (4.3, 3. , 1.1, 0.1, b'Iris-setosa')
 (5.8, 4. , 1.2, 0.2, b'Iris-setosa') (5.7, 4.4, 1.5, 0.4, b'Iris-setosa')
 (5.4, 3.9, 1.3, 0.4, b'Iris-setosa') (5.1, 3.5, 1.4, 0.3, b'Iris-setosa')
 (5.7, 3.8, 1.7, 0.3, b'Iris-setosa') (5.1, 3.8, 1.5, 0.3, b'Iris-setosa')]


/var/folders/9s/m83p31z54sq2pmb926wsx2yr0000gn/T/ipykernel_81381/2149554865.py:5: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_data = np.genfromtxt(url, delimiter=',', dtype=None)


In [105]:
# 4. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset. 
# Use the iris dataset available from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.dataLinks to an external site.. (20 Points)
petal_width_column = np.array([row[3] for row in iris_data]) #index 4th column for each row (each bracket)
first_occurrence = np.where(petal_width_column > 1.0)[0][0] #find every row and identify the first one
print(first_occurrence)

50


In [103]:
# 5. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
# Input:
# np.random.seed(100)
# a = np.random.uniform(1,50, 20)
# (20 Points)
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print("Original array:\n", a)

b = a
b[b > 30] = 30 # modifiy values that is greater than 30 to 30 
b[b < 10] = 10 # modifiy values that is less than 10 to 10 
print("Modified array:\n", b)

c= np.clip(a,10,30) # there is a np.clip() that does the same thing 
print(c)

Original array:
 [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Modified array:
 [27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
